name: Build & Deploy Angular Docker Image

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-push:
    name: Build and push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the Angular app
        run: |
          # Determina quale configurazione utilizzare per il build
          if [ "${GITHUB_REF}" == "refs/heads/develop" ]; then
            npm run build -- --configuration staging
          else
            npm run build -- --configuration production
          fi

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/taf-fe:${{ github.ref == 'refs/heads/develop' && 'staging' || 'latest' }}

  deploy:
    name: SSH deploy to server
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (for consistency)
        uses: actions/checkout@v4

      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/manager/orchestrator/taf

            # Determina se siamo su staging o produzione
            if [ "${GITHUB_REF}" == "refs/heads/develop" ]; then
              IMAGE_TAG="staging"
              SERVICE="taf-fe-staging"
            else
              IMAGE_TAG="latest"
              SERVICE="taf-fe"
            fi

            # Assicurati che l'immagine sia aggiornata
            docker compose pull $SERVICE

            # Ricrea solo il servizio taf-fe in background
            docker compose up -d $SERVICE
